[package]
name = "novax-rsa"
version = "0.0.1"
edition = "2021"
description = "rsa crypto library for private and public key creation"
license = "Apache-2.0"

[dependencies]
rand = "0.8.5"
rsa = "0.9.6"
