[package]
name = "novax-rdkafka"
version = "0.0.1"
edition = "2021"
description = "an rdkaffa client"
license = "Apache-2.0"
repository = "https://github.com/novax-exchange/common-rs"


[dependencies]
rdkafka = "0.36.2"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
