[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
novax-log = { path="../novax-log" }
novax-services = { path="../novax-services", default-features=false, features=["http"]  }