[package]
name = "novax-sqlx-mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql_async = "0.34.2"
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio"] }

[dev-dependencies]
env_logger = "0.11.5"
log = "0.4.22"
tokio = { version = "1.40.0", features = ["full"] }
