[package]
name = "novax-http"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "a http service stub"

[dependencies]
axum = { version = "0.7.5", features = ["multipart", "macros"] }
thiserror = { workspace = true }
tokio = { version = "1.39.3", features = ["full"] }
