[package]
name = "novax-http"
version = "0.0.1a"
edition = "2021"
license = "Apache-2.0"
description = "a http service stub"

[dependencies]
axum = { version = "0.7.5", features = ["multipart", "macros"] }
novax-tokio = "0.0.1"
thiserror = "1.0.63"
