[package]
name = "novax-grpc"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "a grpc service stub"

[dependencies]
tonic = "0.12.1"
tokio = { version = "1.39.3", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }
