[package]
name = "novax-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.1"
tokio = { version = "1.39.3", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.12.1", features = ["prost"] }
