[package]
name = "novax-grpc"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "a grpc service stub"

[dependencies]
tonic = "0.12.2"
tokio = { version = "1.40.0", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.12.2", features = ["prost"] }
