[package]
name = "novax-reqwest"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "a mutual tls client implementation"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "rustls-tls"] }

[dev-dependencies]
novax-tokio = { version = "0.0.1" }
