[package]
name = "novax-kafka"
version = "0.0.1"
edition = "2021"

[dependencies]
futures = "0.3.30"
rdkafka = { version = "0.36.2", features = ["tokio"] }
tokio = { workspace="true", features=["full"] }