[package]
name = "novax-kafka"
version = "0.0.1"
edition = "2021"
description = "a native kafka client"
license = "Apache-2.0"
repository = "https://github.com/novax-exchange/common-rs"


[dependencies]
kafka = "0.10.0"
rayon = "1.10.0"
tokio = { version = "1.40.0", features = ["full"] }
