name: Action to publish to crate io

on:
  push:
    tags: releases-[w]+/[1-9]+.[0-9]+.[0-9]+
    branches: ["feature/reusable_unit", "main"]
  pull_request:
    branches: ["feature/reusable_unit", "main"]

jobs:
  deploy:
    name: Deploy to crate-io
    # if : startsWith( github.ref, 'refs/tags/releases/')
    runs-on: Ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Login crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
  publish-log:
    needs: deploy
    name: Publishing log
    if: ${{ startsWith(github.ref, 'refs/tags/releases-log') }}
    step:
      run: cargo publish -p novax-log
    
  publish-http:
    needs: deploy
    name: Publishing http services
    if: ${{ startsWith(github.ref, 'refs/tags/releases-http') }}
    steps:
      run: cargo publish -p novax-http
    
  publish-grpc:
    needs: deploy
    name: Publishing grpc services
    if: ${{ startsWith(github.ref, 'refs/tags/releases-grpc') }}
    steps:
      run: cargo publish -p novax-grpc

