name: Publish to crate.io

on:
  workflow_dispatch:

jobs:
  log:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-log
    secrets: inherit
  http:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-http
    secrets: inherit
  https:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-https
    secrets: inherit
  grpc:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-grpc
    secrets: inherit
  grpcs:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-grpcs
    secrets: inherit
  mysql:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-sqlx-mysql
    secrets: inherit
  postgres:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-sqlx-postgres
    secrets: inherit
  reqwest:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-reqwest
    secrets: inherit
  rsa:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-rsa
    secrets: inherit
  rsa-async:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-rsa-async
    secrets: inherit
  signature:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-signature
    secrets: inherit
  tokio:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-tokio
    secrets: inherit