name: Action to publish to crate io

on: workflow_dispatch

jobs:
  log:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-log
    secrets: inherit

  http:
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: novax-http
    secrets: inherit

  grpc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-rs@main
      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: cargo publish -p novax-grpc

  sqlx-mysql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-rs@main
      - name: Login crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: cargo publish -p novax-sqlx-mysql

  sqlx-postgres:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-rs@main
      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: cargo publish -p novax-sqlx-postgres
  tokio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/setup-rs@main
      - run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - run: cargo publish -p novax-tokio