name: Action to publish to crate io

on:
  workflow_dispatch:
  push:


jobs:


  publish:
    strategy:
      matrix:
        name: [novax-log, novax-http, novax-grpc, novax-sqlx-mysql, novax-sqlx-postgres, novax-tokio]
    uses: novax-exchange/common-rs/.github/workflows/common-publish.yaml@main
    with:
      name: ${{matrix.name}}
    secrets: inherit
