name: Action to publish to crate io

on:
  push:
    branches: ["feature/reusable_unit", "main"]

jobs:
  deploy:
    name: Deploy to crate-io
    runs-on: Ubuntu-latest
    if: contains( github.event.head_commit.message, 'PUBLISH')
    steps:
      - name: Check out
        uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.PAT_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Login crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publishing log
        if:  contains( github.event.head_commit.message, 'PUBLISH LOG')
        run: cargo publish -p novax-log
      - name: Publishing http services
        if:  contains( github.event.head_commit.message, 'PUBLISH HTTP')
        run: cargo publish -p novax-http
      - name: Publishing grpc services
        if:  contains( github.event.head_commit.message, 'PUBLISH GRPC')
        run: cargo publish -p novax-grpc
      - name: Publishing sqlx-mysql services
        if:  contains( github.event.head_commit.message, 'PUBLISH SQLX MYSQL')
        run: cargo publish -p novax-sqlx-mysql
      - name: Publishing sqlx-postgres services
        if:  contains( github.event.head_commit.message, 'PUBLISH SQLX POSTGRES')
        run: cargo publish -p novax-sqlx-postgres
      - name: Publishing tokios services
        if:  contains( github.event.head_commit.message, 'PUBLISH TOKIO')
        run: cargo publish -p novax-tokio

## remove workspace --> individual release project rather than workspace

