name: Action to publish to crate io

on:
  push:
    tags: releases-[a-z]+/[1-9]+.[0-9]+.[0-9]+
    branches: ["feature/reusable_unit", "main"]
  pull_request:
    branches: ["feature/reusable_unit", "main"]

jobs:
  deploy:
    name: Deploy to crate-io
    # if : startsWith( github.ref, 'refs/tags/releases/')
    runs-on: Ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Login crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Publishing log
        if: ${{ startsWith(github.ref, 'refs/tags/releases-log') }}
        run: cargo publish -p novax-log
      - name: Publishing http services
        if: ${{ startsWith(github.ref, 'refs/tags/releases-http') }}
        run: cargo publish -p novax-http
      - name: Publishing grpc services
        if: ${{ startsWith(github.ref, 'refs/tags/releases-grpc') }}
        run: cargo publish -p novax-grpc


